<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Company>OnIT</Company>
    <Product>OnIT-SMTP</Product>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
</Project>
